/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wow_learning_jni_JNIProvider */

#ifndef _Included_com_wow_learning_jni_JNIProvider
#define _Included_com_wow_learning_jni_JNIProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wow_learning_jni_JNIProvider
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wow_learning_jni_JNIProvider_getName
  (JNIEnv *, jclass);

/*
 * Class:     com_wow_learning_jni_JNIProvider
 * Method:    getCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wow_learning_jni_JNIProvider_getCount
  (JNIEnv *, jclass);

/*
 * Class:     com_wow_learning_jni_JNIProvider
 * Method:    getMoney
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wow_learning_jni_JNIProvider_getMoney
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
