/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wow_learning_JniActivity */

#ifndef _Included_com_wow_learning_JniActivity
#define _Included_com_wow_learning_JniActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wow_learning_JniActivity
 * Method:    getStrFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wow_learning_jni_JniActivity_getStrFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
